fix call signature of Domain.delete_record
fixes this error in the test suite:

        def delete(self):
    >       return self.domain.delete_record(self.id)
    E       TypeError: delete_record() missing 1 required positional argument: 'record'

    skiff/Domain.py:25: TypeError